### ISSUE TITLE
Bug:  There is insufficient memory for the Java Runtime Environment to continue.

### ISSUE THREAD

**Issue by fx10007** [openimsdk/openim-docker#26]
### What happened?

description：kafka failed to start when deploying with docker compose
 
kafka  | # There is insufficient memory for the Java Runtime Environment to continue.
kafka  | # Native memory allocation (mmap) failed to map 1073741824 bytes for committing reserved memory.
kafka  | # An error report file with more information is saved as:
kafka  | # //hs_err_pid31767.log
kafka  | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 1073741824, 0) failed; error='Not enough space' (errno=12)
kafka  | Waiting for Kafka to be ready...
kafka  | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 1073741824, 0) failed; error='Not enough space' (errno=12)
kafka  | #
kafka  | # There is insufficient memory for the Java Runtime Environment to continue.

### What did you expect to happen?

 error='Not enough space'

### How can we reproduce it (as minimally and precisely as possible)?

system：Ubuntu 18.04.6 LTS
cpu：2vCPU x86_64
internal storage：2 GiB
disk：40G

### version

<details>
```console
$ {openim-docker} version
# 3
```
</details>

### Cloud provider

<details>
aliyun
</details>

### OS version

<details>
```system：Ubuntu 18.04.6 LTS
cpu：2vCPU x86_64
internal storage：2 GiB
disk：40G
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
## Issue Analysis

Your Kafka service, when deployed with Docker Compose, fails to start due to memory constraints. Here are the key points from the error:

+ `There is insufficient memory for the Java Runtime Environment to continue.`: This indicates that the Java runtime environment lacks adequate memory to proceed.
+ `Native memory allocation (mmap) failed to map 1073741824 bytes for committing reserved memory.`: Native memory allocation is trying to map 1GB of memory but is unsuccessful.
+ Your system has 2GB RAM, and Kafka is attempting to use 1GB, which might be straining the available memory, especially considering the OS and other processes also require memory.

------

## Solutions

1. **Increase RAM**: If you're operating in a cloud environment, consider resizing your instance to have more RAM. More RAM will alleviate the memory constraints faced by Kafka.

2. **Optimize Java Heap Size**: Adjust Kafka's Java heap size settings. You can set the maximum heap size for JVM (using the `-Xmx` option). Ensure that the memory allocated to Kafka is less than the total memory, leaving some breathing space for the system and other processes.

   ```
   KAFKA_HEAP_OPTS="-Xmx768m -Xms256m"
   ```

3. **Monitor Other Processes**: Use tools like `top` or `htop` to see which processes consume significant memory. Consider if some of them can be stopped to free up memory.

4. **Startup Order**: If you have multiple services in your docker-compose file, ensure Kafka isn't starting first. Let other lower-memory consuming services start before Kafka.
